config/routes.rb
Rails.application.routes.draw do
  resources :schools

  resources :payment_methods

  resources :levels

  resources :sections

  resources :grades

  resources :subscriptions

  devise_for :users
  get 'static_pages/home'

  root 'static_pages#home'

end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  lastname         :string(255)
#  grade_id         :integer
#  section_id       :integer
#  level_id         :integer
#  paymentmethod_id :integer
#  school_id        :integer
#  active           :boolean
#  fechaingreso     :date
#  fechainactivo    :date
#  created_at       :datetime
#  updated_at       :datetime
#

class Subscription < ActiveRecord::Base


  belongs_to :school
  belongs_to :level
  belongs_to :section
  belongs_to :payment_method
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:name, :lastname, :grade_id, :section_id, :level_id, :paymentmethod_id, :school_id, :active, :fechaingreso, :fechainactivo)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @subscription.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h4>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lastname, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lastname, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :section_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :section_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :level_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :level_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payment_method_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :payment_method_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :school_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :school_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :active, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :active, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fechaingreso, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :fechaingreso, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fechainactivo, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :fechainactivo, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<div class="page-header">
  <%= link_to subscriptions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @subscription, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing subscription</h1>
</div>

<%= render 'form' %>

app/views/subscriptions/index.html.erb
<div class="page-header">
  <%= link_to new_subscription_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Subscription
  <% end %>
  <h1>Listing subscriptions</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Lastname</th>
            <th>Section</th>
            <th>Level</th>
            <th>Paymentmethod</th>
            <th>School</th>
            <th>Active</th>
            <th>Fechaingreso</th>
            <th>Fechainactivo</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @subscriptions) do |subscription| %>
            <td><%= subscription.name %></td>
            <td><%= subscription.lastname %></td>
            <td><%= subscription.section.name if subscription.section %></td>
            <td><%= subscription.level.name if subscription.level %></td>
            <td><%= subscription.payment_method.name if subscription.payment_method %></td>
            <td><%= subscription.school.name %></td>
            <td><%= subscription.active %></td>
            <td><%= subscription.fechaingreso %></td>
            <td><%= subscription.fechainactivo %></td>
            <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/subscriptions/new.html.erb
<div class="page-header">
  <%= link_to subscriptions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New subscription</h1>
</div>

<%= render 'form' %>

app/views/subscriptions/show.html.erb
<div class="page-header">
  <%= link_to subscriptions_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_subscription_path(@subscription), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show subscription</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @subscription.name %></dd>

  <dt>Lastname:</dt>
  <dd><%= @subscription.lastname %></dd>


  <dt>Section:</dt>
  <dd><%= @subscription.section_id %></dd>

  <dt>Level:</dt>
  <dd><%= @subscription.level_id %></dd>

  <dt>Paymentmethod:</dt>
  <dd><%= @subscription.paymentmethod_id %></dd>

  <dt>School:</dt>
  <dd><%= @subscription.school_id %></dd>

  <dt>Active:</dt>
  <dd><%= @subscription.active %></dd>

  <dt>Fechaingreso:</dt>
  <dd><%= @subscription.fechaingreso %></dd>

  <dt>Fechainactivo:</dt>
  <dd><%= @subscription.fechainactivo %></dd>

</dl>